baseurl = "/"
languageCode = "en-us"

theme = "digitalgarden"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 2
[[menu.social]]
  name = 'LinkedIn'
  url = 'https://www.linkedin.com/in/mikhail-kochegarov/'
  weight = 1  
[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/NexoMichael'
  weight = 2

title = "Mikhail Kochegarov, software architect / developer / API engineer"
[Params]
    description = "Mikhail Kochegarov's personal blog"
    footer = "[Github](https://github.com/nexo.dev)"
    custom_css = ["css/theme-override.css"]
